CREATE SCHEMA IF NOT EXISTS EZ_FASTFOOD_CATALOG;

SET search_path TO EZ_FASTFOOD_CATALOG;

CREATE TABLE IF NOT EXISTS CATEGORY (
    id BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS PRODUCT (
    id BIGSERIAL PRIMARY KEY,
    category_id BIGINT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    price DECIMAL(10, 2) NOT NULL,
    FOREIGN KEY (category_id) REFERENCES EZ_FASTFOOD_CATALOG.CATEGORY(id) ON DELETE CASCADE
);

INSERT INTO EZ_FASTFOOD_CATALOG.CATEGORY (name)
VALUES
    ('LANCHE'),
    ('ACOMPANHAMENTO'),
    ('BEBIDA'),
    ('SOBREMESA');

INSERT INTO EZ_FASTFOOD_CATALOG.PRODUCT (name, description, price, category_id)
VALUES
    ('X-BURGUER', 'CARNE BOVINA, QUEIJO PRATA, ALFACE, TOMATE, CEBOLA E MOLHO DA CASA', 20.50, 1),
    ('X-FRANGO', 'FILE DE FRANGO EMPANADO, MUÇARELA, ALFACE, TOMATE, BACON, CEBOLA E MOLHO DA CASA', 19.50, 1),
    ('COCA-COLA', 'REFRIGERANTE DE 300 ML', 5.50, 3),
    ('TUTU', 'REFRIGERENTE DE GARRAFA DAS ANTIGAS', 4.50, 3),
    ('BATATA FRITA', 'FRITAS ONDULADAS', 11.90, 2),
    ('PETIT GATEAU', 'TIRA GOSTO', 7.00, 4);
