apiVersion: v1
kind: Service
metadata:
  name: ezfastfood-api-service
spec:
  type: ClusterIP # Internal communication
  selector:
    app: ezfastfood
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
